name: ROS Qt Creator plugin clazy checks

on:
  push:
    paths-ignore: ["**.md"]
  pull_request:
    paths-ignore: ["**.md"]


jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:25.04
      env:
        DEBIAN_FRONTEND: noninteractive

    steps:
      - name: install sudo
        run: |
          apt update
          apt -y install --no-install-recommends sudo

      - uses: actions/checkout@v6

      - name: install Qt and Qt Creator
        run: |
          sudo apt -y install --no-install-recommends python3 python3-pip gcc libpython3-dev
          pip install --break-system-packages pyyaml requests py7zr==0.21 tqdm_loggable
          ./install-sdk.py --export_variables
          cat env >> $GITHUB_ENV

      - name: install system dependencies
        run: |
          sudo apt -y install --no-install-recommends cmake ninja-build libgio-2.0-dev
          sudo apt -y install --no-install-recommends libgl1-mesa-dev ninja-build libutf8proc-dev libcups2-dev
          sudo apt -y install --no-install-recommends clazy

      - name: build plugin
        env:
          CLAZY_CHECKS: "level2,no-old-style-connect,no-rule-of-three,no-ctor-missing-parent-argument,no-no-module-include"
        run: |
          cmake -B build -G Ninja -D CMAKE_PREFIX_PATH="${{ env.QTC_PATH }};${{ env.QT_PATH }}" -D CMAKE_CXX_COMPILER=clazy -D BUILD_ROSTERMINAL=OFF
          cmake --build build --target package
